spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:15432/auth_db?currentSchema=auth
    username: authuser
    password: authpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariDataSource

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: rejestrowanie_uzytkownika:events.authservice.infrastracture.adapters.driven.event.dto.RejestrowanieUzytkownikaZdarzenie
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        check_nullability: true
        default_schema: auth
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    default-schema: auth
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

server:
  port: 8000
  servlet:
    context-path: /api


application:
  jwt:
    secret-key: MzE5d0FzN0ZQcDJyOUlYZnlpU2R5V0FLQXhGNWRtMHc
    expiration-ms: 3600000
  system:
    user:
      uuid: 3f4b1a54-8e3e-4e3c-9f31-0b4a4d7d8d21

logging:
  level:
    web: debug
    org.apache.kafka: WARN